repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
        args: ["--unsafe"]
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: trailing-whitespace
      - id: check-json
      - id: pretty-format-json
        exclude: |
          (?x)^(
          models/notebooks/.*|
          examples/langchain/.*\.ipynb
          )$
        args:
          - "--autofix"
          - "--indent=2"
          - "--no-sort-keys"


  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
      - id: shellcheck

  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", --line-length=99]

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3
        # args: ["--exclude", "<FOO>", "--line-length", "99"]

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        exclude: |
          (?x) (
          )
    #   - id: flake8
    #     files: ^<FOO_DIR>
    #     args: [--append-config, <FOO_DIR>/.flake8]

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.8.7
    hooks:
      - id: nbqa-isort
        args: ["--profile=black", --line-length=99]
      - id: nbqa-black

  - repo: https://github.com/mwouts/jupytext
    rev: v1.16.4b  # CURRENT_TAG/COMMIT_HASH
    hooks:
      - id: jupytext
        args: [--sync]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
      - id: markdownlint
      - id: markdownlint-fix

# Terrafrom

  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.18.0"
    hooks:
      - id: terraform-docs-go
        args: ["markdown", "table", "--output-file", "README.md", "./"]
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: "v1.92.1"
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
        args:
        - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
      - id: terraform_validate
      - id: terraform_tfsec
